include:
    - project: 'brandonbutler/templates'
      file: 
        - '/templates/golang.yml'
        - '/templates/kaniko.yml'
      #  - '/templates/helm.yml'
    - project: 'brandonbutler/templates'
      ref: 'helm-package'
      file: 
        - '/templates/helm.yml'
    - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - build
  - package
  - deploy

build:
  stage: build
  extends: .go-build

kaniko-build:
  extends: .kaniko-build
  stage: package

helm-package:
  extends: .helm-package
  stage: package

deploy:
  stage: deploy
  extends: .helm-deploy
  environment: 
    name: default
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
